server.port=8080

#message directory
spring.messages.basename=i18n/messages
# Spring AI Vector Store (PGVector)
# This will automatically create the vector_store table in Postgres
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.index-type=HNSW